apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  annotations:
    manifestival: new
  creationTimestamp: "2020-01-10T09:40:48Z"
  generation: 1
  name: nodejs-express-build-push-pipeline
  namespace: kabanero
  ownerReferences:
  - apiVersion: kabanero.io/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Collection
    name: nodejs-express
    uid: 3da92cc1-338d-11ea-a855-0a0f498bf672
  resourceVersion: "50562"
  selfLink: /apis/tekton.dev/v1alpha1/namespaces/kabanero/pipelines/nodejs-express-build-push-pipeline
  uid: 4811fa27-338d-11ea-a855-0a0f498bf672
spec:
  resources:
  - name: git-source
    type: git
  - name: docker-image
    type: image
  tasks:
  - name: build-push-task
    resources:
      inputs:
      - name: git-source
        resource: git-source
      outputs:
      - name: docker-image
        resource: docker-image
    taskRef:
      name: nodejs-express-build-push-task
  - name: image-scan-task
    resources:
      inputs:
      - name: git-source
        resource: git-source
      - name: docker-image
        resource: docker-image
    runAfter:
    - build-push-task
    taskRef:
      name: nodejs-express-image-scan-task
