---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: bulldok-image
spec:
  type: image
  params:
  - name: url
    value: image-registry.openshift-image-registry.svc:5000/akka/sam-bulldok
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: bulldok-git
spec:
  type: git
  params:
  - name: url
    value: https://github.com/iamnogada/sam-bulldok.git